backend:
  name: github
  repo: JakePartusch/milo

publish_mode: editorial_workflow

media_folder: content/images
public_folder: /images/uploads

collections:
  - name: blog
    label: "Blog Post"
    folder: "content/posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    format: frontmatter
    fields:
      - { name: category, label: Category, widget: "select" }
      - { name: title, label: Title }
      - { name: subTitle, label: subTitle }
      - { name: cover, label: Cover, widget: "image", required: false, default: "avatars/fallback.png" }
      - { name: body, label: "Blog Post Content", widget: "markdown"}