backend:
  name: github
  repo: JakePartusch/milo

media_folder: content/posts
public_folder: /

collections:
  - name: blog
    label: "Blog Post"
    folder: "content/posts"
    slug: "{{year}}-{{month}}-{{day}}--{{slug}}"
    create: true
    fields:
      - { name: category, label: Category}
      - { name: title, label: Title }
      - { name: subTitle, label: subTitle }
      - { name: cover, label: Cover, widget: "image"}
      - { name: slug, label: Slug }
      - { name: body, label: "Blog Post Content", widget: "markdown"}