backend:
  name: git-gateway
  accept_roles:
    - admin

media_folder: content/posts/images
public_folder: images
collections:
  - name: blog
    label: "Blog Post"
    folder: "content/posts"
    slug: "{{year}}-{{month}}-{{day}}--{{slug}}"
    create: true
    fields:
      - { name: category, label: Category}
      - { name: title, label: Title }
      - { name: subTitle, label: subTitle }
      - { name: cover, label: Cover, widget: "image"}
      - { name: date, label: Date, widget: date }
      - { name: day, label: Day }
      - { name: slug, label: Slug }
      - { name: body, label: "Blog Post Content", widget: "markdown"}